### ISSUE TITLE
TypeError: render_mako() got an unexpected keyword argument 'doctype'

### ISSUE THREAD

**Issue by ltrillaud** [TurboGears/tgext.pluggable#1]
tgext.pluggable doesn't work with turbogears 2.2.0 with mako as default renderer.

Step to reproduce : 
- generate an app with mako un Turbogears2Frozen2.2.0
- create a mako that call a partial

The problem is in 
Module tgext.pluggable.utils:42 in **call**

you call tg_render with doctype
return tg_render(template_vars=result, template_engine=engine_name, template_name=template_name, doctype=None)

That doesn't exist in 
Module tg.render:183 in render
kwargs['result'] = render_function(template_name, tg_vars, **kwargs)

and produce exception
TypeError: render_mako() got an unexpected keyword argument 'doctype'

Here is the prototype for mako
def render_mako(template_name, globs, cache_key=None, cache_type=None, cache_expire=None):

A quick and dirty workaround is to remove doctype=None in  tgext.pluggable.utils:42

Thanks

Laurent
